[package]
name = "localns"
description = "Serves DNS records for all of your local services."
version = "1.0.0"
authors = ["Dave Townsend <dtownsend@oxymoronical.com>"]
documentation = "https://localns.readthedocs.io/en/latest/"
repository = "https://github.com/Mossop/localns"
homepage = "https://github.com/Mossop/localns"
license = "MIT"
edition = "2021"
default-run = "localns"

[dependencies]
bollard = { version = "^0.14.0", features = ["ssl"] }
log = "^0.4.17"
flexi_logger = { version = "^0.23.3", features = ["colors"] }
tokio = { version = "1.20.4", features = ["full"] }
serde = "^1.0.159"
serde_yaml = "^0.8.26"
futures = "^0.3.28"
pin-project-lite = "^0.2.8"
reqwest = { version = "^0.11.16", default-features = false, features = ["json", "rustls-tls"] }
notify = "^4.0.17"
trust-dns-server = "^0.22.0"
async-trait = "^0.1.68"
uuid = { version = "^1.4.0", features = ["v4"] }
time = "^0.3.20"
actix-web = "^4.3.1"
