[package]
name = "localns"
version = "1.0.0"
edition = "2021"
default-run = "localns"

[dependencies]
bollard = { version = "^0.12.0", features = ["ssl"] }
log = "^0.4.14"
flexi_logger = { version = "^0.22.3", features = ["colors"] }
tokio = { version = "1.18.0", features = ["full"] }
serde = "^1.0.136"
serde_yaml = "^0.8.23"
futures = "^0.3.21"
pin-project-lite = "^0.2.8"
reqwest = { version = "^0.11.9", default-features = false, features = ["json", "rustls-tls"] }
notify = "^4.0.17"
trust-dns-server = "^0.21.1"
async-trait = "^0.1.52"
uuid = { version = "^1.0.0", features = ["v4"] }
time = "^0.3.7"
actix-web = "^4.0.1"
